baseURL = 'https://oluceps.github.io/hugo-theme-willow/'
languageCode = 'en-us'
title = '裏柳'
theme = 'willow'

[params]
# when (.Site.Params.hideLevel >= .Params.hideLevel) hide
hideLevel = 0

[[menu.main]]
url = "/about"
name = "关于"
weight = 3

[[menu.main]]
url = "/categories"
name = "目录"
weight = 2

[[menu.main]]
url = "/tags"
name = "标签"
weight = 1

[markup]
  [markup.tableOfContents]
    startLevel = 1
    ordered = false
    endLevel = 4

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'catppuccin-latte'
    tabWidth = 4


